# src/constants.py

SECTOR_TRANSLATION = {
    "Communication Services": "Dịch vụ Truyền thông",
    "Consumer Discretionary": "Hàng tiêu dùng không thiết yếu",
    "Consumer Staples": "Hàng tiêu dùng thiết yếu",
    "Energy": "Năng lượng",
    "Financials": "Tài chính",
    "Health Care": "Chăm sóc sức khỏe",
    "Industrials": "Công nghiệp",
    "Information Technology": "Công nghệ thông tin",
    "Materials": "Nguyên vật liệu",
    "Real Estate": "Bất động sản",
    "Utilities": "Tiện ích công cộng"
}

# SECTOR_TRANSLATION ={
#     "Independent Power and Renewable Electricity Producers": "Nhà sản xuất điện độc lập & Năng lượng tái tạo",
#     "NULL": "Không xác định",
#     "Metals & Mining": "Khai khoáng & Kim loại",
#     "Construction & Engineering": "Xây dựng & Kỹ thuật",
#     "Construction Materials": "Vật liệu xây dựng",
#     "Textiles, Apparel & Luxury Goods": "Dệt may, May mặc & Hàng xa xỉ",
#     "Containers & Packaging": "Bao bì & Đóng gói",
#     "Water Utilities": "Tiện ích nước / Cấp thoát nước",
#     "Real Estate Management & Development": "Quản lý & Phát triển bất động sản",
#     "Financial Services": "Dịch vụ tài chính",
#     "Oil, Gas & Consumable Fuels": "Dầu khí & Nhiên liệu tiêu thụ",
#     "Professional Services": "Dịch vụ chuyên nghiệp",
#     "Pharmaceuticals": "Dược phẩm",
#     "Energy Equipment & Services": "Thiết bị & Dịch vụ năng lượng",
#     "Transportation Infrastructure": "Hạ tầng giao thông",
#     "Industrial Conglomerates": "Tập đoàn công nghiệp",
#     "Specialty Retail": "Bán lẻ chuyên doanh",
#     "Capital Markets": "Thị trường vốn",
#     "Chemicals": "Hóa chất",
#     "Communications Equipment": "Thiết bị truyền thông",
#     "Ground Transportation": "Vận tải đường bộ",
#     "IT Services": "Dịch vụ CNTT",
#     "Trading Companies & Distributors": "Công ty thương mại & Nhà phân phối",
#     "Beverages": "Đồ uống",
#     "Household Products": "Sản phẩm chăm sóc gia đình",
#     "Marine Transportation": "Vận tải biển",
#     "Banks": "Ngân hàng",
#     "Health Care Providers & Services": "Nhà cung cấp & Dịch vụ chăm sóc sức khỏe",
#     "Hotels, Restaurants & Leisure": "Khách sạn, Nhà hàng & Giải trí",
#     "Distributors": "Nhà phân phối",
#     "Food Products": "Thực phẩm",
#     "Air Freight & Logistics": "Vận tải hàng không & Logistics",
#     "Electrical Equipment": "Thiết bị điện",
#     "Household Durables": "Đồ gia dụng lâu bền",
#     "Media": "Truyền thông",
#     "Health Care Equipment & Supplies": "Thiết bị & Vật tư y tế",
#     "Insurance": "Bảo hiểm",
#     "Diversified Consumer Services": "Dịch vụ tiêu dùng đa dạng",
#     "Machinery": "Máy móc",
#     "Gas Utilities": "Tiện ích khí đốt",
#     "Electronic Equipment, Instruments & Components": "Thiết bị, Dụng cụ & Linh kiện điện tử",
#     "Passenger Airlines": "Hàng không chở khách",
#     "Building Products": "Sản phẩm xây dựng",
#     "Paper & Forest Products": "Sản phẩm giấy & Lâm sản",
#     "Software": "Phần mềm",
#     "Leisure Products": "Sản phẩm giải trí",
#     "Electric Utilities": "Tiện ích điện lực",
#     "Commercial Services & Supplies": "Dịch vụ & Vật tư thương mại",
#     "Entertainment": "Giải trí",
#     "Automobile Components": "Phụ tùng ô tô",
#     "Tobacco": "Thuốc lá",
#     "Diversified Telecommunication Services": "Dịch vụ viễn thông đa dạng",
#     "Automobiles": "Ô tô"
# }